"""
Preprocessing and feature engineering utilities for healthcare insurance data.
"""

from __future__ import annotations

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


CATEGORICAL_COLS = ["region", "employment_type", "plan_type"]
NUMERICAL_COLS = [
    "age",
    "bmi",
    "num_dependents",
    "smoker",
    "pre_existing_conditions",
    "previous_claims",
    "annual_income",
    "exercise_frequency",
    "chronic_conditions",
    "mental_health_history",
]


def encode_categoricals(df: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, LabelEncoder]]:
    """Label-encode categorical columns in-place.

    Args:
        df: Input DataFrame containing categorical columns.

    Returns:
        Tuple of (encoded DataFrame, dict mapping column name to fitted LabelEncoder).
    """
    df = df.copy()
    encoders: dict[str, LabelEncoder] = {}
    for col in CATEGORICAL_COLS:
        if col in df.columns:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col].astype(str))
            encoders[col] = le
    return df, encoders


def apply_encoders(df: pd.DataFrame, encoders: dict[str, LabelEncoder]) -> pd.DataFrame:
    """Apply pre-fitted label encoders to a DataFrame.

    Args:
        df: Input DataFrame.
        encoders: Dictionary of fitted LabelEncoders keyed by column name.

    Returns:
        DataFrame with encoded categorical columns.
    """
    df = df.copy()
    for col, le in encoders.items():
        if col in df.columns:
            known = set(le.classes_)
            df[col] = df[col].apply(lambda x: x if x in known else le.classes_[0])
            df[col] = le.transform(df[col].astype(str))
    return df


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add derived features useful for premium prediction.

    New features:
        age_bmi_interaction: age * bmi product capturing joint risk.
        risk_score: composite risk score from several binary risk factors.
        income_to_age_ratio: proxy for socioeconomic life-stage factor.

    Args:
        df: Input DataFrame (must contain raw numerical columns).

    Returns:
        DataFrame with additional engineered features.
    """
    df = df.copy()
    df["age_bmi_interaction"] = df["age"] * df["bmi"]
    df["risk_score"] = (
        df["smoker"]
        + df["chronic_conditions"]
        + df["mental_health_history"]
        + (df["pre_existing_conditions"] > 0).astype(int)
        + (df["previous_claims"] > 2).astype(int)
        + (df["bmi"] >= 30).astype(int)
    )
    df["income_to_age_ratio"] = df["annual_income"] / (df["age"] + 1)
    return df


def scale_features(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
) -> tuple[np.ndarray, np.ndarray, StandardScaler]:
    """Fit a StandardScaler on training data and transform both splits.

    Args:
        X_train: Training feature matrix.
        X_test: Test feature matrix.

    Returns:
        Tuple of (scaled X_train, scaled X_test, fitted scaler).
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled, X_test_scaled, scaler


def prepare_dataset(
    df: pd.DataFrame,
    target_col: str = "annual_premium",
    test_size: float = 0.2,
    random_state: int = 42,
) -> dict:
    """Full preprocessing pipeline: encode, engineer, split, scale.

    Args:
        df: Raw DataFrame (as generated by generate_healthcare_data).
        target_col: Name of the target column.
        test_size: Fraction of data to reserve for testing.
        random_state: Random seed.

    Returns:
        Dictionary with keys:
            X_train, X_test, y_train, y_test (numpy arrays),
            X_train_df, X_test_df (DataFrames before scaling),
            encoders, scaler, feature_names.
    """
    X_raw = df.drop(columns=[target_col])
    y = df[target_col].values

    X_enc, encoders = encode_categoricals(X_raw)
    X_feat = engineer_features(X_enc)
    feature_names = list(X_feat.columns)

    X_tr_df, X_te_df, y_train, y_test = train_test_split(
        X_feat, y, test_size=test_size, random_state=random_state
    )
    X_train, X_test, scaler = scale_features(X_tr_df, X_te_df)

    return {
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test,
        "X_train_df": X_tr_df,
        "X_test_df": X_te_df,
        "encoders": encoders,
        "scaler": scaler,
        "feature_names": feature_names,
    }
